### ISSUE TITLE
bin2xml problem

### ISSUE THREAD

**Issue by mrchrisster** [acc-/tplink-archer-c2300#5] opened 2020-02-09 04:30 UTC
I have a c2300 and would like to try ssh access.
I have openssl with zlib compiled on Ubuntu 18
When running the script I receive error:
140442015024960:error:29065064:lib(41):bio_zlib_read:zlib inflate error:crypto/comp/c_zlib.c:397:zlib error:data error

Any idea what this could be?

**Comment by acc-** [comment] 2020-02-09 08:14
Hard to say, you could try to execute individual commands that script does to find out where the issue is.

Do you have c2300 v1 or v2? Which firmware version do you have?

**Comment by mrchrisster** [comment] 2020-02-09 09:04
Thanks for your feedback! I'm trying v1 with latest firmware Archer C2300(US)_V1_180611.
I first tried compiling on Mac OSX and after that spitting out the error I mentioned above, I installed Ubuntu to see if it was something Mac related. Same error on both platforms . I ran the decompiling code manually but couldn't get anymore insight as to why zlib is complaining. I'll try an older firmware tomorrow and report back. Just out of interest, besides the Openvpn client, did you ever try opkg or Luci on the router?

**Comment by acc-** [comment] 2020-02-09 10:29
I have v1 EU, but that shouldn't be a difference. 

It looks the problem is with your zlib build... Try this approach:
1. Make sure OPENSSL variable points to proper openssl binary (might be default one without zlib)
2. Install pigz (http://zlib.net/pigz/) - On debian 10 it was accessible in package repository
3. Modify these lines in bin2xml to use pigz instead of openssl zlib
`$OPENSSL aes-256-cbc -d $AES -in $IN | $OPENSSL zlib -d -out $TMP/mid.bin`
to:
`$OPENSSL aes-256-cbc -d $AES -in $IN | pigz -d >$TMP/mid.bin`
and
`$OPENSSL aes-256-cbc -d $AES -in $TMP/orig.bin | $OPENSSL zlib -d -out $OUT`
to
`$OPENSSL aes-256-cbc -d $AES -in $TMP/orig.bin | pigz -d >$OUT`

4. Modify xml2bin in the smiliar way:
`cat $IN | $OPENSSL zlib | $OPENSSL aes-256-cbc $AES -out $TMP/orig.bin`
to
`cat $IN | pigz -z | $OPENSSL aes-256-cbc $AES -out $TMP/orig.bin`
and
`$OPENSSL zlib -in $TMP/mid.bin | $OPENSSL aes-256-cbc $AES -out $OUT`
to
`pigz -cz  $TMP/mid.bin | $OPENSSL aes-256-cbc $AES -out $OUT`

**Comment by acc-** [comment] 2020-02-09 10:34
And no, I didn't try luci. This firware is quite ancient OpenWRT, I didn't want to break anything, besides I didn't need it :)

**Comment by mrchrisster** [comment] 2020-02-09 16:38
Unfortunately pigz doesnt seem to recognize the bin structure:

```
./bin2xml.sh c2300v1_us-up-2.0.3_Build_20180611_Rel.77668_sign_2018-06-12_09.58.27.bin 
pigz: skipping: <stdin> unrecognized format
error writing output file
File MD5: , product MD5: b37598ac5105ea9974fc6634a4c92a76
MD5 product name mismatch, beware when using xml2bin !!!
bad decrypt
140673161115456:error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length:crypto/evp/evp_enc.c:525:
pigz: skipping: <stdin> empty
XML file saved in c2300v1_us-up-2.0.3_Build_20180611_Rel.77668_sign_2018-06-12_09.58.27.xml
root@christoph-MacBookPro:~/Desktop/c2300# which openssl
/usr/local/bin/openssl
root@christoph-MacBookPro:~/Desktop/c2300# 
```

**Comment by acc-** [comment] 2020-02-09 16:42
Wait... what are you giving as input parameter? Firmware binary ?

You need to download your router backup from your router web pages... Advanced / System Tools / Backup & Restore and pass this binary file as input to the script.

**Comment by mrchrisster** [comment] 2020-02-09 16:47
Oh man, I feel stupid. This obviously worked on first try!
I was already wondering why I could decompile firmware binary to xml code, didnt make much sense to me :)
Anyways thanks so much for sharing your findings and helping me out, much appreciated!

**Comment by acc-** [comment] 2020-02-09 16:49
No worries, closing this ticket then :)

**Closed as completed by acc-** 2020-02-09 16:49 UTC
